# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  autoupdate_commit_msg: "CI: pre-commit autoupdate"
  skip: [pyright]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        name: Trims trailing whitespace.
        exclude: AristaAppForSplunk/SplunkForwarder/autom4te.cache
      - id: end-of-file-fixer
        name: Ensures that a file is either empty, or ends with one newline.
        exclude_types: [svg, json]
